import {
  LanguagePack,
  VocabularyTerm,
  UniversalLesson,
  Worksheet,
  Flashcard,
  LocalStory,
  NipunOutcome,
  CommunicationCard,
  StudentProfile,
} from '../types';

export const LANGUAGE_PACKS: LanguagePack[] = [
  {
    id: 'santhali',
    name: 'Santhali',
    nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ',
    script: 'Ol Chiki (ᱚᱞ ᱪᱤᱠᱤ)',
    translationReady: true,
    audioReady: true,
    vocabularyCount: 2450,
    lessonsCount: 48,
    worksheetsCount: 32,
    sizeMB: 420,
    downloaded: true,
    lastUpdated: 'Today, 10:30 AM',
  },
  {
    id: 'ho',
    name: 'Ho',
    nativeName: 'ᱦᱚ: ᱡᱟᱜᱟᱨ',
    script: 'Warang Citi (ᱣᱟᱨᱟᱝ ᱪᱤᱛᱤ)',
    translationReady: true,
    audioReady: true,
    vocabularyCount: 1820,
    lessonsCount: 35,
    worksheetsCount: 24,
    sizeMB: 380,
    downloaded: false,
    lastUpdated: '1 week ago',
  },
  {
    id: 'mundari',
    name: 'Mundari',
    nativeName: 'ᱢᱩᱱᱰᱟᱨᱤ',
    script: 'Mundari Bani (ᱢᱩᱱᱰᱟᱨᱤ ᱵᱟᱱᱤ)',
    translationReady: true,
    audioReady: true,
    vocabularyCount: 1640,
    lessonsCount: 30,
    worksheetsCount: 20,
    sizeMB: 350,
    downloaded: false,
    lastUpdated: '2 weeks ago',
  },
];

export const EDUCATION_GLOSSARY: VocabularyTerm[] = [
  // Numbers
  {
    id: 'num_1',
    category: 'Mathematics',
    hindi: 'एक',
    targetLangText: { santhali: 'ᱢᱤᱫ', ho: 'ᱢᱤᱫ', mundari: 'ᱢᱤᱫ' },
    scriptText: { santhali: 'ᱢᱤᱫ (1)', ho: 'ᱢᱤᱫ', mundari: 'ᱢᱤᱫ' },
    phonetic: { santhali: 'Mit', ho: 'Miyad', mundari: 'Miya' },
    exampleHindi: 'एक सेब दिखाओ।',
    exampleTarget: { santhali: 'ᱢᱤᱫ ᱥᱮᱣ ᱩᱫᱩᱜ ᱢᱮ', ho: 'ᱢᱤᱫ ᱥᱮᱣ ᱩᱫᱩᱜ ᱢᱮ', mundari: 'ᱢᱤᱫ ᱥᱮᱣ ᱩᱫᱩᱜ ᱢᱮ' },
  },
  {
    id: 'num_2',
    category: 'Mathematics',
    hindi: 'दो',
    targetLangText: { santhali: 'ᱵᱟᱨ', ho: 'ᱵᱟᱨ', mundari: 'ᱵᱟᱨ' },
    scriptText: { santhali: 'ᱵᱟᱨ (2)', ho: 'ᱵᱟᱨ', mundari: 'ᱵᱟᱨ' },
    phonetic: { santhali: 'Bar', ho: 'Baria', mundari: 'Baria' },
    exampleHindi: 'दो पेंसिल लो।',
    exampleTarget: { santhali: 'ᱵᱟᱨ ᱯᱮᱱᱥᱤᱞ ᱦᱟᱛᱟᱣ ᱢᱮ', ho: 'ᱵᱟᱨ ᱯᱮᱱᱥᱤᱞ ᱦᱟᱛᱟᱣ ᱢᱮ', mundari: 'ᱵᱟᱨ ᱯᱮᱱᱥᱤᱞ ᱦᱟᱛᱟᱣ ᱢᱮ' },
  },
  {
    id: 'num_3',
    category: 'Mathematics',
    hindi: 'तीन',
    targetLangText: { santhali: 'ᱯᱮ', ho: 'ᱯᱮ', mundari: 'ᱯᱮ' },
    scriptText: { santhali: 'ᱯᱮ (3)', ho: 'ᱯᱮ', mundari: 'ᱯᱮ' },
    phonetic: { santhali: 'Pe', ho: 'Peya', mundari: 'Peya' },
  },
  {
    id: 'num_4',
    category: 'Mathematics',
    hindi: 'चार',
    targetLangText: { santhali: 'ᱯᱩᱱ', ho: 'ᱯᱩᱱ', mundari: 'ᱯᱩᱱ' },
    scriptText: { santhali: 'ᱯᱩᱱ (4)', ho: 'ᱯᱩᱱ', mundari: 'ᱯᱩᱱ' },
    phonetic: { santhali: 'Pun', ho: 'Upun', mundari: 'Upun' },
  },
  {
    id: 'num_5',
    category: 'Mathematics',
    hindi: 'पांच',
    targetLangText: { santhali: 'ᱢᱚᱬᱮ', ho: 'ᱢᱚᱬᱮ', mundari: 'ᱢᱚᱬᱮ' },
    scriptText: { santhali: 'ᱢᱚᱬᱮ (5)', ho: 'ᱢᱚᱬᱮ', mundari: 'ᱢᱚᱬᱮ' },
    phonetic: { santhali: 'Monre', ho: 'Moba', mundari: 'Monre' },
  },
  {
    id: 'math_add',
    category: 'Mathematics',
    hindi: 'जोड़ो',
    targetLangText: { santhali: 'ᱢᱮᱥᱟᱭ ᱢᱮ', ho: 'ᱢᱮᱥᱟᱭ ᱢᱮ', mundari: 'ᱡᱚᱲᱟᱣ ᱢᱮ' },
    scriptText: { santhali: 'ᱢᱮᱥᱟᱭ ᱢᱮ', ho: 'ᱢᱮᱥᱟᱭ ᱢᱮ', mundari: 'ᱡᱚᱲᱟᱣ ᱢᱮ' },
    phonetic: { santhali: 'Mesay me', ho: 'Mesai me', mundari: 'Joraw me' },
    exampleHindi: 'दो और तीन को जोड़ो।',
    exampleTarget: { santhali: 'ᱵᱟᱨ ᱟᱨ ᱯᱮ ᱢᱮᱥᱟᱭ ᱢᱮ', ho: 'ᱵᱟᱨ ᱟᱨ ᱯᱮ ᱢᱮᱥᱟᱭ ᱢᱮ', mundari: 'ᱵᱟᱨ ᱟᱨ ᱯᱮ ᱡᱚᱲᱟᱣ ᱢᱮ' },
  },
  {
    id: 'math_count',
    category: 'Mathematics',
    hindi: 'गिणो',
    targetLangText: { santhali: 'ᱞᱮᱠᱷᱟᱭ ᱢᱮ', ho: 'ᱞᱮᱠᱷᱟᱭ ᱢᱮ', mundari: 'ᱞᱮᱠᱷᱟᱭ ᱢᱮ' },
    scriptText: { santhali: 'ᱞᱮᱠᱷᱟᱭ ᱢᱮ', ho: 'ᱞᱮᱠᱷᱟᱭ ᱢᱮ', mundari: 'ᱞᱮᱠᱷᱟᱭ ᱢᱮ' },
    phonetic: { santhali: 'Lekhay me', ho: 'Lekhai me', mundari: 'Lekhai me' },
    exampleHindi: 'चीजों को गिनो और बताओ।',
    exampleTarget: { santhali: 'ᱡᱤᱱᱤᱥ ᱠᱚ ᱞᱮᱠᱷᱟᱭ ᱢᱮ ᱟᱨ ᱞᱟᱹᱭ ᱢᱮ', ho: 'ᱡᱤᱱᱤᱥ ᱠᱚ ᱞᱮᱠᱷᱟᱭ ᱢᱮ', mundari: 'ᱡᱤᱱᱤᱥ ᱠᱚ ᱞᱮᱠᱷᱟᱭ ᱢᱮ' },
  },
  // Colors
  {
    id: 'col_red',
    category: 'Environment',
    hindi: 'लाल',
    targetLangText: { santhali: 'ᱟᱨᱟ custom', ho: 'ᱟᱨᱟ', mundari: 'ᱟᱨᱟ' },
    scriptText: { santhali: 'ᱟᱨᱟ', ho: 'ᱟᱨᱟ', mundari: 'ᱟᱨᱟ' },
    phonetic: { santhali: 'Ara', ho: 'Ara', mundari: 'Ara' },
  },
  {
    id: 'col_green',
    category: 'Environment',
    hindi: 'हरा',
    targetLangText: { santhali: 'ᱦᱟᱹᱨᱤᱭᱟᱹᱲ', ho: 'ᱦᱟᱹᱨᱤᱭᱟᱹᱲ', mundari: 'ᱦᱟᱹᱨᱤᱭᱟᱹᱲ' },
    scriptText: { santhali: 'ᱦᱟᱹᱨᱤᱭᱟᱹᱲ', ho: 'ᱦᱟᱹᱨᱤᱭᱟᱹᱲ', mundari: 'ᱦᱟᱹᱨᱤᱭᱟᱹᱲ' },
    phonetic: { santhali: 'Hariyar', ho: 'Hariyar', mundari: 'Hariyar' },
  },
  {
    id: 'col_blue',
    category: 'Environment',
    hindi: 'नीला',
    targetLangText: { santhali: 'ᱞᱤᱞ', ho: 'ᱞᱤᱞ', mundari: 'ᱞᱤᱞ' },
    scriptText: { santhali: 'ᱞᱤᱞ', ho: 'ᱞᱤᱞ', mundari: 'ᱞᱤᱞ' },
    phonetic: { santhali: 'Lil', ho: 'Lil', mundari: 'Lil' },
  },
  // Classroom Instructions
  {
    id: 'instr_open',
    category: 'Classroom instructions',
    hindi: 'किताब खोलो',
    targetLangText: { santhali: 'ᱯᱩᱛᱷᱤ ᱡᱷᱤᱡᱽ ᱢᱮ', ho: 'ᱯᱩᱛᱷᱤ ᱡᱷᱤᱡᱽ ᱢᱮ', mundari: 'ᱯᱩᱛᱷᱤ ᱡᱷᱤᱡᱽ ᱢᱮ' },
    scriptText: { santhali: 'ᱯᱩᱛᱷᱤ ᱡᱷᱤᱡᱽ ᱢᱮ', ho: 'ᱯᱩᱛᱷᱤ ᱡᱷᱤᱡᱽ ᱢᱮ', mundari: 'ᱯᱩᱛᱷᱤ ᱡᱷᱤᱡᱽ ᱢᱮ' },
    phonetic: { santhali: 'Puthi jhij me', ho: 'Puthi jhij me', mundari: 'Puthi jhij me' },
  },
  {
    id: 'instr_sit',
    category: 'Classroom instructions',
    hindi: 'बैठ जाओ',
    targetLangText: { santhali: 'ᱫᱩᱲᱩᱵ ᱢᱮ', ho: 'ᱫᱩᱲᱩᱵ ᱢᱮ', mundari: 'ᱫᱩᱲᱩᱵ ᱢᱮ' },
    scriptText: { santhali: 'ᱫᱩᱲᱩᱵ ᱢᱮ', ho: 'ᱫᱩᱲᱩᱵ ᱢᱮ', mundari: 'ᱫᱩᱲᱩᱵ ᱢᱮ' },
    phonetic: { santhali: 'Durup me', ho: 'Durup me', mundari: 'Durup me' },
  },
  {
    id: 'instr_listen',
    category: 'Classroom instructions',
    hindi: 'ध्यान से सुनो',
    targetLangText: { santhali: 'ᱟᱸᱡᱚᱢ ᱢᱮ', ho: 'ᱟᱸᱡᱚᱢ ᱢᱮ', mundari: 'ᱟᱸᱡᱚᱢ ᱢᱮ' },
    scriptText: { santhali: 'ᱟᱸᱡᱚᱢ ᱢᱮ', ho: 'ᱟᱸᱡᱚᱢ ᱢᱮ', mundari: 'ᱟᱸᱡᱚᱢ ᱢᱮ' },
    phonetic: { santhali: 'Anjom me', ho: 'Anjom me', mundari: 'Anjom me' },
  },
  {
    id: 'obj_tree',
    category: 'Environment',
    hindi: 'पेड़',
    targetLangText: { santhali: 'ᱫᱟᱨᱮ', ho: 'ᱫᱟᱨᱮ', mundari: 'ᱫᱟᱨᱮ' },
    scriptText: { santhali: 'ᱫᱟᱨᱮ', ho: 'ᱫᱟᱨᱮ', mundari: 'ᱫᱟᱨᱮ' },
    phonetic: { santhali: 'Dare', ho: 'Dare', mundari: 'Dare' },
  },
  {
    id: 'obj_water',
    category: 'Daily conversation',
    hindi: 'पानी',
    targetLangText: { santhali: 'ᱫᱟ custom', ho: 'ᱫᱟ custom', mundari: 'ᱫᱟ custom' },
    scriptText: { santhali: 'ᱫᱟ custom', ho: 'ᱫᱟ custom', mundari: 'ᱫᱟ custom' },
    phonetic: { santhali: 'Daah', ho: 'Daah', mundari: 'Daah' },
  },
  {
    id: 'obj_cow',
    category: 'Environment',
    hindi: 'गाय',
    targetLangText: { santhali: 'ᱰᱟᱝᱜᱽᱨᱤ', ho: 'ᱰᱟᱝᱜᱽᱨᱤ', mundari: 'ᱰᱟᱝᱜᱽᱨᱤ' },
    scriptText: { santhali: 'ᱰᱟᱝᱜᱽᱨᱤ', ho: 'ᱰᱟᱝᱜᱽᱨᱤ', mundari: 'ᱰᱟᱝᱜᱽᱨᱤ' },
    phonetic: { santhali: 'Dangri', ho: 'Dangri', mundari: 'Dangri' },
  },
];

export const MOCK_UNIVERSAL_LESSON: UniversalLesson = {
  id: 'lesson_numbers_c1',
  title: 'Counting Numbers 1 to 10 with Sal Leaves',
  grade: 'class_1',
  subject: 'mathematics',
  targetLang: 'santhali',
  createdAt: '2026-09-16',
  learningObjective: 'Students will identify, count, and speak numbers 1 to 10 in both Hindi and Santhali using natural objects.',
  hindiExplanation: 'आज हम 1 से 10 तक की संख्याएं सीखेंगे। अपने सामने रखी सखुआ (साल) की पत्तियों को गिनो।',
  tribalExplanation: 'ᱛᱮᱦᱮᱧ ᱵᱚᱱ ᱪᱮᱫᱟ ᱑ ᱠᱷᱚᱱ ᱑᱐ ᱦᱟᱹᱵᱤᱡ ᱞᱮᱠᱷᱟ᱾ ᱟᱯᱮ ᱥᱟᱢᱟᱝ ᱨᱮ ᱢᱮᱱᱟᱜ ᱥᱟᱨᱡᱚᱢ ᱥᱟᱠᱟᱢ ᱞᱮᱠᱷᱟᱭ ᱯᱮ᱾',
  tribalScript: '᱑ ᱠᱷᱚᱱ ᱑᱐ ᱦᱟᱹᱵᱤᱡ ᱞᱮᱠᱷᱟ (Ol Chiki)',
  phoneticScript: 'Tehenj bon cheda 1 khon 10 habij lekha. Ape samang re menag sarjom sakam lekhay pe.',
  teacherScript: 'Teacher says: "बच्चों, मेरे साथ बोलो - 1 (Mit), 2 (Bar), 3 (Pe)..."',
  visualExamples: [
    { title: 'Mit (One)', symbol: '🍃', description: 'One Sal leaf / ᱢᱤᱫ ᱥᱟᱠᱟᱢ' },
    { title: 'Bar (Two)', symbol: '🍃 🍃', description: 'Two Sal leaves / ᱵᱟᱨ ᱥᱟᱠᱟᱢ' },
    { title: 'Pe (Three)', symbol: '🍃 🍃 🍃', description: 'Three Sal leaves / ᱯᱮ ᱥᱟᱠᱟᱢ' },
    { title: 'Pun (Four)', symbol: '🍃 🍃 🍃 🍃', description: 'Four Sal leaves / ᱯᱩᱱ ᱥᱟᱠᱟᱢ' },
    { title: 'Monre (Five)', symbol: '🍃 🍃 🍃 🍃 🍃', description: 'Five Sal leaves / ᱢᱚᱬᱮ ᱥᱟᱠᱟᱢ' },
  ],
  audioNarrationText: 'Mit, Bar, Pe, Pun, Monre! One, two, three, four, five!',
  flashcards: [
    { hindi: 'एक (1)', target: 'ᱢᱤᱫ', phonetic: 'Mit', symbol: '1️⃣' },
    { hindi: 'दो (2)', target: 'ᱵᱟᱨ', phonetic: 'Bar', symbol: '2️⃣' },
    { hindi: 'तीन (3)', target: 'ᱯᱮ', phonetic: 'Pe', symbol: '3️⃣' },
    { hindi: 'चार (4)', target: 'ᱯᱩᱱ', phonetic: 'Pun', symbol: '4️⃣' },
    { hindi: 'पांच (5)', target: 'ᱢᱚᱬᱮ', phonetic: 'Monre', symbol: '5️⃣' },
  ],
  interactiveActivity: {
    title: 'Sal Leaf Collector Game',
    instructions: 'Collect leaves in the school yard and arrange them in groups of 3 and 5.',
    steps: [
      'Divide students into pairs.',
      'Ask team A to show "Bar" (2) fingers and team B to show "Pe" (3) leaves.',
      'Combine them and say "Monre" (5) together in Santhali.',
    ],
  },
  worksheet: {
    title: 'Match Objects with Santhali Numbers',
    instructions: 'Count the flowers/leaves and draw a line to the correct Santhali Ol Chiki number.',
    questions: [
      'Count 🍎 🍎 -> Match with ᱵᱟᱨ (Bar)',
      'Count 🌳 🌳 🌳 -> Match with ᱯᱮ (Pe)',
      'Count 🔴 -> Match with ᱢᱤᱫ (Mit)',
    ],
  },
  quiz: [
    { question: 'Santhali for number 3 (तीन) is?', options: ['Mit', 'Bar', 'Pe', 'Pun'], answerIndex: 2 },
    { question: 'What does "Mit" (ᱢᱤᱫ) mean in Hindi?', options: ['एक', 'दो', 'तीन', 'चार'], answerIndex: 0 },
    { question: 'Count the leaves: 🍃 🍃. In Santhali it is?', options: ['Monre', 'Bar', 'Pun', 'Pe'], answerIndex: 1 },
  ],
  assessment: 'Check if child can count up to 5 orally in Santhali and point to the matching leaf cluster.',
  homework: 'Collect 5 pebbles at home and explain "Monre" to your parents.',
  accessibilityAlternatives: {
    visual: 'Provide tactile wooden tokens or clay beads so visually impaired children can count by feeling.',
    hearing: 'Use visual flashcards with large 1️⃣ 2️⃣ symbols and sign gestures.',
    communication: 'Use the "Speak Without Speaking" board button "1", "2", "3" for non-verbal response.',
  },
  culturalExamples: [
    'Counting Sal (Sarjom) leaves collected during Baha Festival.',
    'Counting Sohrai art patterns drawn on village mud walls.',
  ],
  nipunOutcomeId: 'nipun_num_1',
};

export const MOCK_WORKSHEETS: Worksheet[] = [
  {
    id: 'ws_01',
    title: 'Grade 1 Math: Counting 1 to 5',
    grade: 'class_1',
    subject: 'mathematics',
    topic: 'Numbers 1-5',
    targetLang: 'santhali',
    difficulty: 'Beginner',
    createdAt: '2026-09-16',
    instructionsHindi: 'गिणो और सही संथाली संख्या लिखो।',
    instructionsTarget: 'ᱞᱮᱠᱷᱟᱭ ᱢᱮ ᱟᱨ ᱥᱟᱹᱦᱤ ᱥᱟᱱᱛᱟᱲᱤ ᱞᱮᱠᱷᱟ ᱚᱞ ᱢᱮ',
    questions: [
      {
        id: 'q1',
        type: 'counting',
        questionHindi: 'सेबों की संख्या कितनी है?',
        questionTarget: 'ᱥᱮᱣ ᱞᱮᱠᱷᱟᱭ ᱢᱮ',
        phonetic: 'Sew lekhay me',
        symbolOrImage: '🍎 🍎 🍎',
        correctAnswer: 'ᱯᱮ (Pe / 3)',
        countTarget: 3,
      },
      {
        id: 'q2',
        type: 'match',
        questionHindi: 'संख्या 1 (एक) को संथाली शब्द से मिलाओ',
        questionTarget: '᱑ (एक) ᱢᱤᱫ ᱥᱟᱶᱛᱮ ᱡᱚᱲᱟᱣ ᱢᱮ',
        phonetic: 'Mit (1)',
        options: ['ᱢᱤᱫ (Mit)', 'ᱵᱟᱨ (Bar)', 'ᱯᱮ (Pe)'],
        correctAnswer: 'ᱢᱤᱫ (Mit)',
      },
      {
        id: 'q3',
        type: 'trace',
        questionHindi: 'संथाली अंक "᱑" (Mit) को ट्रेस करो और रंग भरो',
        questionTarget: 'Ol Chiki "᱑" trace me',
        phonetic: 'Mit',
        symbolOrImage: '᱑',
      },
      {
        id: 'q4',
        type: 'fill_in_blanks',
        questionHindi: 'खाली जगह भरो: 1, __, 3, 4, 5 (Hindi: दो / Santhali: ___)',
        questionTarget: 'Mit, ___, Pe, Pun, Monre',
        phonetic: 'Mit, Bar, Pe...',
        options: ['ᱵᱟᱨ (Bar)', 'ᱯᱩᱱ (Pun)', 'ᱢᱚᱬᱮ (Monre)'],
        correctAnswer: 'ᱵᱟᱨ (Bar)',
      },
    ],
  },
];

export const MOCK_FLASHCARDS: Flashcard[] = [
  { id: 'fc_1', category: 'Animals', hindi: 'गाय (Cow)', target: 'ᱰᱟᱝᱜᱽᱨᱤ', phonetic: 'Dangri', symbolOrImage: '🐄', audioText: 'Dangri' },
  { id: 'fc_2', category: 'Environment', hindi: 'पेड़ (Tree)', target: 'ᱫᱟᱨᱮ', phonetic: 'Dare', symbolOrImage: '🌳', audioText: 'Dare' },
  { id: 'fc_3', category: 'Daily', hindi: 'पानी (Water)', target: 'ᱫᱟ custom', phonetic: 'Daah', symbolOrImage: '💧', audioText: 'Daah' },
  { id: 'fc_4', category: 'Colors', hindi: 'लाल (Red)', target: 'ᱟᱨᱟ', phonetic: 'Ara', symbolOrImage: '🔴', audioText: 'Ara' },
  { id: 'fc_5', category: 'Numbers', hindi: 'एक (One)', target: 'ᱢᱤᱫ', script: '᱑', phonetic: 'Mit', symbolOrImage: '1️⃣', audioText: 'Mit' },
  { id: 'fc_6', category: 'Numbers', hindi: 'दो (Two)', target: 'ᱵᱟᱨ', script: '᱒', phonetic: 'Bar', symbolOrImage: '2️⃣', audioText: 'Bar' },
  { id: 'fc_7', category: 'Classroom', hindi: 'किताब (Book)', target: 'ᱯᱩᱛᱷᱤ', phonetic: 'Puthi', symbolOrImage: '📚', audioText: 'Puthi' },
  { id: 'fc_8', category: 'Body', hindi: 'हाथ (Hand)', target: 'ᱛᱤ', phonetic: 'Ti', symbolOrImage: '✋', audioText: 'Ti' },
];

export const MOCK_STORIES: LocalStory[] = [
  {
    id: 'story_sal_tree',
    titleHindi: 'सखुआ के पेड़ का जादू',
    titleTarget: 'ᱥᱟᱨᱡᱚᱢ ᱫᱟᱨᱮ ᱨᱮᱱᱟᱜ ᱡᱟᱹᱫᱩ',
    phoneticTitle: 'Sarjom Dare Renag Jadu',
    theme: 'Forest',
    grade: 'class_2',
    targetLang: 'santhali',
    contentHindi: [
      'एक सुंदर गांव में पिंकी और उसका दोस्त बिरसा रहते थे।',
      'वे हर दिन सखुआ (साल) के जंगल में खेलने जाते थे।',
      'एक दिन उन्होंने जंगल में एक छोटी गौरैया देखी जो रो रही थी।',
      'पिंकी ने पूछा: "तुम्हें क्या हुआ?" गौरैया ने कहा: "मुझे प्यास लगी है!"',
      'बिरसा ने बहती नदी से पानी लाया और गौरैया को पिलाया। गौरैया खुशी से गाने लगी!',
    ],
    contentTarget: [
      'ᱢᱤᱫ ᱥᱚᱨᱮᱥ ᱟᱹᱛᱩ ᱨᱮ ᱯᱤᱝᱠᱤ ᱟᱨ ᱟᱡᱤᱡ ᱜᱟᱛᱮ ᱵᱤᱨᱥᱟ ᱠᱤᱱ ᱛᱟᱦᱮᱸ ᱠᱟᱱᱟ᱾',
      'ᱟᱹᱠᱤᱱ ᱫᱤᱱᱚᱢ ᱦᱤᱞᱚᱜ ᱥᱟᱨᱡᱚᱢ ᱵᱤᱨ ᱛᱮ ᱮᱱᱮᱡ ᱠᱤᱱ ᱥᱮᱱᱚᱜ-ᱟ᱾',
      'ᱢᱤᱫ ᱫᱤᱱ ᱵᱤᱨ ᱨᱮ ᱢᱤᱫ ᱠᱟᱹᱴᱤᱡ ᱪᱮᱬᱮ ᱠᱤᱱ ᱧᱮᱞ ᱠᱮᱫᱮᱭᱟ ᱡᱟᱦᱟᱸᱭ ᱫᱚᱭ ᱨᱟᱜ ᱮᱫ ᱛᱟᱦᱮᱸᱱ᱾',
      'ᱯᱤᱝᱠᱤ ᱭᱮ ᱠᱩᱞᱤ ᱠᱮᱫᱮᱭᱟ: "ᱪᱮᱫ ᱦᱩᱭ ᱟᱠᱟᱱᱟ?" ᱪᱮᱬᱮ ᱭᱮ ᱞᱟᱹᱭ ᱠᱮᱫᱟ: "ᱤᱧ ᱛᱮᱛᱟᱝ ᱟᱠᱟᱫ ᱤᱧᱟ!"',
      'ᱵᱤᱨᱥᱟ ᱫᱚ ᱜᱟᱰᱟ ᱠᱷᱚᱱ ᱫᱟ custom ᱟᱹᱜᱩ ᱠᱟᱛᱮ ᱪᱮᱬᱮ ᱭᱮ ᱧᱩ ᱟᱫᱮᱭᱟ᱾ ᱪᱮᱬᱮ ᱨᱟᱹᱥᱠᱟᱹ ᱛᱮ ᱥᱮᱨᱮᱧ ᱮ ᱮᱦᱚᱵ ᱠᱮᱫᱟ!',
    ],
    phoneticContent: [
      'Mit sores atu re Pinki ar ajij gate Birsa kin tahe kana.',
      'Akin dinom hilog Sarjom bir te enej kin senog-a.',
      'Mit din bir re mit katij chene kin njel kedeya jahay doy rag ed tahen.',
      'Pinki ye kuli kedeya: "Ched huy akan-a?" Chene ye lay keda: "Inj tetang akad inja!"',
      'Birsa do gada khon daah agu kate chene ye nju adeya. Chene Raska te serenj e ehob keda!',
    ],
    illustrations: ['🏡', '🌳', '🐦', '💧', '🎵'],
    comprehensionQuestions: [
      {
        questionHindi: 'कहानी में बच्चों का क्या नाम था?',
        questionTarget: 'ᱠᱟᱦᱱᱤ ᱨᱮ ᱜᱤᱫᱽᱨᱟᱹ ᱣᱟᱜ ᱧᱩᱛᱩᱢ ᱪᱮᱫ ᱛᱟᱦᱮᱸ ᱠᱟᱱᱟ?',
        options: ['पिंकी और बिरसा', 'राजू और रोहन', 'अमित और सोहन'],
        answerIndex: 0,
      },
      {
        questionHindi: 'गौरैया को क्या चाहिए था?',
        questionTarget: 'ᱪᱮᱬᱮ ᱪᱮᱫ ᱞᱟᱹᱠᱛᱤ ᱛᱟᱦᱮᱸ ᱠᱟᱱᱟ?',
        options: ['खाना', 'पानी (Daah)', 'खिलौना'],
        answerIndex: 1,
      },
    ],
    culturalDisclaimer: 'Note: AI-generated fictional story inspired by Jharkhand forest ecosystems for mother-tongue reading practice.',
  },
];

export const NIPUN_OUTCOMES: NipunOutcome[] = [
  {
    id: 'nipun_num_1',
    code: 'FLN-M1.2',
    category: 'Number Sense',
    grade: 'class_1',
    title: 'Counts objects up to 10 in mother tongue & Hindi',
    description: 'Student can recite number names 1-10 sequentially and map concrete physical objects (beads, leaves, stones) to exact quantity.',
    suggestedActivity: 'Count 5 Sal leaves together in Santhali (Mit, Bar, Pe, Pun, Monre) and Hindi.',
    suggestedPractice: 'Universal Lesson #1 (Counting 1-10 with Sal Leaves)',
  },
  {
    id: 'nipun_lang_1',
    code: 'FLN-L1.1',
    category: 'Oral Language',
    grade: 'class_1',
    title: 'Understands basic classroom instructions in mother tongue',
    description: 'Student comprehends teacher commands like "Open book", "Sit down", "Listen" spoken in Santhali/Ho/Mundari.',
    suggestedActivity: 'Live Voice Translation classroom game: "Durup me" (Sit down).',
    suggestedPractice: 'Emergency Classroom Phrasebook practice.',
  },
  {
    id: 'nipun_read_2',
    code: 'FLN-R2.3',
    category: 'Reading',
    grade: 'class_2',
    title: 'Reads short bilingual picture stories with comprehension',
    description: 'Reads 3-4 sentence stories in mother tongue script (Ol Chiki/Latin) and answers simple questions.',
    suggestedActivity: 'Local Story Studio: "Sarjom Dare Renag Jadu" reading circle.',
    suggestedPractice: 'AI Story Studio comprehension quiz.',
  },
];

export const COMMUNICATION_CARDS: CommunicationCard[] = [
  { id: 'c1', labelHindi: 'हाँ (Yes)', labelTarget: 'ᱦᱮᱸ (Hen)', phonetic: 'Hen', symbol: '✅', category: 'basic', audioText: 'Hen' },
  { id: 'c2', labelHindi: 'नहीं (No)', labelTarget: 'ᱵᱟᱝ (Bang)', phonetic: 'Bang', symbol: '❌', category: 'basic', audioText: 'Bang' },
  { id: 'c3', labelHindi: 'पानी चाहिए (Water)', labelTarget: 'ᱫᱟ custom ᱞᱟᱹᱠᱛᱤ', phonetic: 'Daah lakti', symbol: '💧', category: 'needs', audioText: 'Daah lakti' },
  { id: 'c4', labelHindi: 'खाना चाहिए (Food)', labelTarget: 'ᱡᱚᱢᱟᱜ ᱞᱟᱹᱠᱛᱤ', phonetic: 'Jomag lakti', symbol: '🍲', category: 'needs', audioText: 'Jomag lakti' },
  { id: 'c5', labelHindi: 'मदद चाहिए (Help)', labelTarget: 'ᱜᱚᱲᱚ ᱞᱟᱹᱠᱛᱤ', phonetic: 'Goro lakti', symbol: '🆘', category: 'needs', audioText: 'Goro lakti' },
  { id: 'c6', labelHindi: 'शौचालय जाना है (Toilet)', labelTarget: 'ᱴᱚᱭᱞᱮᱴ ᱥᱮᱱᱚᱜ', phonetic: 'Toilet senog', symbol: '🚻', category: 'needs', audioText: 'Toilet senog' },
  { id: 'c7', labelHindi: 'दर्द हो रहा है (Pain)', labelTarget: 'ᱦᱟᱥᱩ ᱤᱧᱟ', phonetic: 'Hasu inja', symbol: '🤕', category: 'feelings', audioText: 'Hasu inja' },
  { id: 'c8', labelHindi: 'दोबारा बोलो (Repeat)', labelTarget: 'ᱟᱨᱦᱚᱸ ᱞᱟᱹᱭ ᱢᱮ', phonetic: 'Arho lay me', symbol: '🔄', category: 'classroom', audioText: 'Arho lay me' },
  { id: 'c9', labelHindi: 'समझ आ गया (Understand)', labelTarget: 'ᱵᱩᱡᱷᱟᱹᱣ ᱠᱮᱫᱟᱹᱧ', phonetic: 'Bujhaw kedanj', symbol: '💡', category: 'classroom', audioText: 'Bujhaw kedanj' },
  { id: 'c10', labelHindi: 'समझ नहीं आया (Don\'t understand)', labelTarget: 'ᱵᱟᱹᱧ ᱵᱩᱡᱷᱟᱹᱣ ᱠᱮᱫᱟ', phonetic: 'Banj bujhaw keda', symbol: '❓', category: 'classroom', audioText: 'Banj bujhaw keda' },
  { id: 'c11', labelHindi: 'खुश हूँ (Happy)', labelTarget: 'ᱨᱟᱹᱥᱠᱟᱹ ᱜᱮᱭᱟᱹᱧ', phonetic: 'Raska geyanj', symbol: '😊', category: 'feelings', audioText: 'Raska geyanj' },
  { id: 'c12', labelHindi: 'थक गया (Tired)', labelTarget: 'ᱞᱟᱸᱜᱟ ᱭᱮᱱᱟᱹᱧ', phonetic: 'Langa yenanj', symbol: '🥱', category: 'feelings', audioText: 'Langa yenanj' },
];

export const EMERGENCY_PHRASES = [
  { hindi: 'क्या तुम ठीक हो?', target: 'ᱟᱢ ᱴᱷᱤᱠ ᱜᱮᱭᱟᱢ?', phonetic: 'Am thik geyam?', symbol: '🩺' },
  { hindi: 'क्या तुम्हें मदद चाहिए?', target: 'ᱟᱢ ᱜᱚᱲᱚ ᱞᱟᱹᱠᱛᱤ ᱟᱢᱟ?', phonetic: 'Am goro lakti ama?', symbol: '🤝' },
  { hindi: 'पानी पीओ।', target: 'ᱫᱟ custom ᱧᱩᱭ ᱢᱮ', phonetic: 'Daah njoy me', symbol: '🥛' },
  { hindi: 'यहाँ बैठो।', target: 'ᱱᱚᱸᱰᱮ ᱫᱩᱲᱩᱵ ᱢᱮ', phonetic: 'Node durup me', symbol: '🪑' },
  { hindi: 'यहाँ आओ।', target: 'ᱱᱚᱸᱰᱮ ᱦᱤᱡᱩᱜ ᱢᱮ', phonetic: 'Node hijug me', symbol: '👉' },
  { hindi: 'ध्यान से सुनो।', target: 'ᱟᱸᱡᱚᱢ ᱢᱮ', phonetic: 'Anjom me', symbol: '👂' },
  { hindi: 'दोबारा बोलो।', target: 'ᱟᱨᱦᱚᱸ ᱞᱟᱹᱭ ᱢᱮ', phonetic: 'Arho lay me', symbol: '🔁' },
  { hindi: 'बहुत अच्छे!', target: 'ᱟᱹᱰᱤ ᱱᱟᱯᱟᱭ!', phonetic: 'Adi napay!', symbol: '⭐' },
  { hindi: 'फिर से कोशिश करो।', target: 'ᱟᱨᱦᱚᱸ ᱠᱩᱨᱩᱢᱩᱴᱩᱭ ᱢᱮ', phonetic: 'Arho kurumutuy me', symbol: '💪' },
  { hindi: 'अपनी किताब खोलो।', target: 'ᱟᱢᱟᱜ ᱯᱩᱛᱷᱤ ᱡᱷᱤᱡᱽ ᱢᱮ', phonetic: 'Amag puthi jhij me', symbol: '📖' },
  { hindi: 'किताब बंद करो।', target: 'ᱯᱩᱛᱷᱤ ᱵᱚᱸᱫᱚᱭ ᱢᱮ', phonetic: 'Puthi bondoy me', symbol: '📕' },
];

export const TEACHER_10_WORDS = [
  { hindi: 'पानी (Water)', target: 'ᱫᱟ custom (Daah)', phonetic: 'Daah', sentenceHindi: 'पानी पीओ', sentenceTarget: 'ᱫᱟ custom ᱧᱩᱭ ᱢᱮ' },
  { hindi: 'खाना (Food)', target: 'ᱡᱚᱢᱟᱜ (Jomag)', phonetic: 'Jomag', sentenceHindi: 'खाना खाओ', sentenceTarget: 'ᱡᱚᱢᱟᱜ ᱡᱚᱢ ᱢᱮ' },
  { hindi: 'बैठो (Sit)', target: 'ᱫᱩᱲᱩᱵ (Durup)', phonetic: 'Durup', sentenceHindi: 'यहाँ बैठो', sentenceTarget: 'ᱱᱚᱸᱰᱮ ᱫᱩᱲᱩᱵ ᱢᱮ' },
  { hindi: 'खड़े हो (Stand)', target: 'ᱛᱤᱸᱜᱩ (Tingu)', phonetic: 'Tingu', sentenceHindi: 'खड़े हो जाओ', sentenceTarget: 'ᱛᱤᱸᱜᱩᱱ ᱢᱮ' },
  { hindi: 'सुनो (Listen)', target: 'ᱟᱸᱡᱚᱢ (Anjom)', phonetic: 'Anjom', sentenceHindi: 'मेरी बात सुनो', sentenceTarget: 'ᱤᱧᱟᱜ ᱠᱟᱛᱷᱟ ᱟᱸᱡᱚᱢ ᱢᱮ' },
  { hindi: 'आओ (Come)', target: 'ᱦᱤᱡᱩᱜ (Hijug)', phonetic: 'Hijug', sentenceHindi: 'पास आओ', sentenceTarget: 'ᱥᱩᱨ ᱦᱤᱡᱩᱜ ᱢᱮ' },
  { hindi: 'जाओ (Go)', target: 'ᱥᱮᱱᱚᱜ (Senog)', phonetic: 'Senog', sentenceHindi: 'जगह पर जाओ', sentenceTarget: 'ᱴᱷᱟᱶ ᱛᱮ ᱥᱮᱱᱚᱜ ᱢᱮ' },
  { hindi: 'किताब (Book)', target: 'ᱯᱩᱛᱷᱤ (Puthi)', phonetic: 'Puthi', sentenceHindi: 'किताब निकालो', sentenceTarget: 'ᱯᱩᱛᱷᱤ ᱚᱰᱚᱠ ᱢᱮ' },
  { hindi: 'संख्या (Number)', target: 'ᱞᱮᱠᱷᱟ (Lekha)', phonetic: 'Lekha', sentenceHindi: 'संख्या बताओ', sentenceTarget: 'ᱞᱮᱠᱷᱟ ᱞᱟᱹᱭ ᱢᱮ' },
  { hindi: 'अच्छा (Good)', target: 'ᱱᱟᱯᱟᱭ (Napay)', phonetic: 'Napay', sentenceHindi: 'बहुत अच्छा', sentenceTarget: 'ᱟᱹᱰᱤ ᱱᱟᱯᱟᱭ' },
];

export const MOCK_STUDENTS: StudentProfile[] = [
  { id: 's1', pseudonym: 'Student 01 (Birsa)', grade: 'class_1', preferredLang: 'santhali', learningLevel: 7, completedActivities: 14, strugglingTopics: [], lastActive: 'Today' },
  { id: 's2', pseudonym: 'Student 02 (Pinki)', grade: 'class_1', preferredLang: 'santhali', learningLevel: 4, completedActivities: 8, strugglingTopics: ['Numbers 6-10'], lastActive: 'Today' },
  { id: 's3', pseudonym: 'Student 03 (Somra)', grade: 'class_2', preferredLang: 'ho', learningLevel: 8, completedActivities: 22, strugglingTopics: [], lastActive: 'Yesterday' },
  { id: 's4', pseudonym: 'Student 04 (Sunita)', grade: 'class_2', preferredLang: 'santhali', learningLevel: 5, completedActivities: 11, strugglingTopics: ['Subtraction'], lastActive: 'Today' },
  { id: 's5', pseudonym: 'Student 05 (Mangal)', grade: 'class_3', preferredLang: 'mundari', learningLevel: 6, completedActivities: 16, strugglingTopics: ['Grammar'], lastActive: '3 days ago' },
];
